title: Rajas Gujarathi
description: DevOps Engineer & AWS Architect
author: Rajas Gujarathi
linkedin_username: rajasgujarathi
twitter_username: rajasgujarathi
url: "https://rajasgujarathi.github.io"
description: >- # this means to ignore newlines until "baseurl:"
  A blog about software development 